const GET_NEWS_REQUEST = 'user/GET_NEWS_REQUEST';

const GET_NEWS_REQUEST_SUCCESS = 'user/GET_NEWS_REQUEST_SUCCESS';
const GET_NEWS_REQUEST_FAILURE = 'user/GET_NEWS_REQUEST_FAILURE';

export {GET_NEWS_REQUEST, GET_NEWS_REQUEST_SUCCESS, GET_NEWS_REQUEST_FAILURE};
