const GET_FAVORITE_NEWS_REQUEST = 'user/GET_FAVORITE_NEWS_REQUEST';

const GET_FAVORITE_NEWS_REQUEST_SUCCESS =
  'user/GET_FAVORITE_NEWS_REQUEST_SUCCESS';
const GET_FAVORITE_NEWS_REQUEST_FAILURE =
  'user/GET_FAVORITE_NEWS_REQUEST_FAILURE';

export {
  GET_FAVORITE_NEWS_REQUEST,
  GET_FAVORITE_NEWS_REQUEST_SUCCESS,
  GET_FAVORITE_NEWS_REQUEST_FAILURE,
};
