const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST';

const GET_USER_INFO_REQUEST_SUCCESS = 'GET_USER_INFO_REQUEST_SUCCESS';
const GET_USER_INFO_REQUEST_FAILURE = 'GET_USER_INFO_REQUEST_FAILURE';

export {
  GET_USER_INFO_REQUEST,
  GET_USER_INFO_REQUEST_SUCCESS,
  GET_USER_INFO_REQUEST_FAILURE,
};
